### ISSUE TITLE
Username identifiers

### ISSUE THREAD

**Issue by JoshuaDietz** [NicoNex/echotron#37]
Hi
I've seen in the documentation that it says the library wants to only use id's because they can not change. But now I have the case that I am building an admin bot where the admin can specify a user by either id or username. As this library only seems to support ids, I don't see how to implement i.e. a ban function where the admin can specify the user to ban by giving the username.

Is this even possible with echotron and if so, how?

Thanks in advance!

**Comment by NicoNex** [comment]
This is currently a limitation of the Telegram API: https://core.telegram.org/bots/api#banchatmember.
There's no way for us to implement that functionality unless Telegram decides to do so.

What you need to do in this case is finding the ID that corresponds to the given username and ban using the ID.
This can be done for example by issuing the command for banning (i.e. `/ban`) quoting that user's message, so that the bot can retrieve the user ID from the quoted message.

I hope you'll find this helpful.
