### ISSUE TITLE
How to run a bot on two or more servers

### ISSUE THREAD

**Issue by GMELUM** [NicoNex/echotron#46]
I have 2 server instances behind a balancer. I need to use Webhook on both servers and receive notifications on one of them.

I use this:
```go
for u := range echotron.WebhookUpdates("https://example.com/bot", token) {
	if u.PreCheckoutQuery != nil && u.PreCheckoutQuery.Currency == "XTR" {
		println(u.PreCheckoutQuery.InvoicePayload)
	}
}
```
but I get a 429 error

**Comment by NicoNex** [comment]
To avoid the error 429 make sure you're using the latest Echotron update that implements a rate limiter on the requests.
Additionally you might want to set the limiter duration to 1/2 of the current values since you're running it on two machines.
Then you can stetup a custom server for both instances and use this function:

```go
// HandleWebhook is the http.HandlerFunc for the webhook URL.
// Useful if you've already a http server running and want to handle the request yourself.
func (d *Dispatcher) HandleWebhook(w http.ResponseWriter, r *http.Request)
```

**Comment by GMELUM** [comment]
panic is caused when trying to call setWebhook. But one of the instances must call it.

**Comment by NicoNex** [comment]
I think what you could do it to call the SetWebhook on your balancer or a third service and then have the two instances instantiate a new dispatcher and create a webserver that calls `HandleWebhook`.

This way the third service (or the balacer itself) is the one receiving the updates from Telegram and then proceeds to route them to the right address.

**Comment by NicoNex** [comment]
What I would do for the Two instances is this:
```go
func main() {
    dsp := echotron.NewDispatcher()
    
    http.HandleFunc("/", dsp.HandleFunc)
    http.ListenAndServe(":8080", nil)
}
```

Then all you have to do is set the actual webhook to Telegram in a middle man that calls one of the two services according to the balancing logic.

**Comment by GMELUM** [comment]
theoretically I can call setWebhook on each of the servers since all servers have the same url? Just handle the error and not cause panic.

**Comment by NicoNex** [comment]
Yes you can do that, but you can't use `dispatcher.ListenWebhook` since it tries to set the webhook and if there's an error it returns without listening.
What you can do is what I showed you in the last snippet which is actually what the `ListenWebhook` does aside setting the webhook to Telegram, this way you'll be actually listening for updates.

**Comment by GMELUM** [comment]
Thank you, everything worked for me. Only now I'm seeing another problem. The same code with a webhook works differently on different bots. On one bot everything works correctly, but on the second I wait a very, very long time for an answer. Some requests don't arrive at all. Perhaps you have a theory of what the problem might be?

**Comment by NicoNex** [comment]
Yes, it could be due to the request limiters, you should try setting different values for [echotron.SetChatRequestLimit](https://pkg.go.dev/github.com/NicoNex/echotron/v3#SetChatRequestLimit) and [echotron.SetGlobalRequestLimit](https://pkg.go.dev/github.com/NicoNex/echotron/v3#SetGlobalRequestLimit).

The current defaults are `time.Minute / 20` for the chat limiter and `time.Second / 30` for the global limiter.

**Comment by NicoNex** [comment]
Maybe in the next release I should disable them by default.

**Comment by GMELUM** [comment]
My problem doesn't appear over time. I just receive a request from Telegram after 5-20 seconds, but on another bot it doesn’t take even 1 second. The code is the same, only the tokens are different.

**Comment by GMELUM** [comment]
The problem was solved as soon as I re-issued a new token for the bot. Thanks for the help again

**Comment by NicoNex** [comment]
No problem, I'm closing this issue but if you have more questions feel free to text in the telegram group dedicated to Echotron, you can find the link to it in the readme ;).
